name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
        ports:
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Preemptive Disk Cleanup
      run: |
        docker system prune -af --volumes
        sudo rm -rf /var/lib/docker/tmp/*
        sudo rm -rf /root/.cache/*
        sudo systemctl restart docker

    - name: Clone the public repository with Docker setup
      run: |
        git clone https://github.com/openinnovationai/recruiting-qa-challenge.git
        cd recruiting-qa-challenge

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Check port availability
      run: |
        sudo netstat -tuln | grep '8000' || echo "Port 8000 is free"

    - name: Wait before starting Docker
      run: sleep 10
    
    - name: Build and start Docker container
      run: |
        cd recruiting-qa-challenge
        docker-compose -f docker-compose.yml up -d

    - name: Wait for the server to start
      run: sleep 30  

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore, build, and test
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release --logger:trx --results-directory ./test-results
      continue-on-error: true  
     
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always() 
      with:
        name: 'Test Results'
        path: '**/*.trx' 
        reporter: dotnet-trx      

    - name: Stop and remove Docker container
      run: |
        cd recruiting-qa-challenge
        docker-compose -f docker-compose.yml down

    - name: Cleanup Docker to free up space
      run: |
        docker system prune -f
        docker volume prune -f
